Development
clin2on3mun/To-do-list-peer-feedback pull request #1
Opened 2023-05-08 13:29 UTC by clin2on3mun

This is the pull request requesting a review from my partner.
it is a TO-DO-LIST project
- [ ] Js best practice
- [ ] DRY,KISS, YAGNI rules
- [ ] HTML & CSS best practice

2023-05-08 16:35 UTC, iamsjunaid requested changes
# Status: Required Changes :recycle:
Hi @clin2on3mun 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-08 16:35 UTC, iamsjunaid commented on src/modules/display.js
> +      // list.id = indexNo;
Please try to avoid pushing comments with the code. You can always return to the previous version using `git history`.

2023-05-08 16:35 UTC, iamsjunaid commented on src/index.html
> +                    </ul>
Please make sure to remove unnecessery spaces from codebase.

2023-05-08 17:46 UTC, clin2on3mun commented on src/index.html
> +                    </ul>
Thank you for reviewing my PR

2023-05-09 07:50 UTC, iamsjunaid commented
Hi @clin2on3mun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media1.giphy.com/media/3ornjXIIShZ2MgyyHu/giphy.gif)

## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Made the requested changes✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

2023-05-09 07:51 UTC, iamsjunaid approved these changes
Hi @clin2on3mun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media1.giphy.com/media/3ornjXIIShZ2MgyyHu/giphy.gif)

## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Made the requested changes✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

2023-05-09 08:04 UTC, merged